baseURL: "/"
languageCode: en-us
title: Boba Blog SF
theme: puppet

menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: -100
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: map
      name: Map
      url: /map.html/
      weight: 30
      permalinks:
        map.html: /map/
    - identifier: bobalytics
      name: Bobalytics
      url: /bobalytics/
      weight: 40
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50

params:
  img_home: "img/home.png"
  img_404: "img/tyler-nix-ArW7pJRYw7Q-unsplash.jpg"
  useFaviconGenerator: true
  description: A place to stay up to date about San Francisco boba and boba-adjacent drinks
  keywords: "blog,boba,san francisco,bubble tea,tea,personal"
  enableRobotsTXT: true

  sidebar:
    enable: true
    avatar: "img/bubble-tea.png"

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "JSON", "RSS"]

permalinks:
  /: /:filename

